### ISSUE TITLE
Slashes are escaped

### ISSUE THREAD

**Issue by psequeirag** [gongo/json-reformat#15]
Hi, I'm using version 20141210.1656 installed from MELPA.

When reformatting some JSON that has forward slashes (like URLs), the reformat escapes them with backward slashes, but I don't think that's strictly necessary and sometimes is in fact undesirable (at least for me).

For example:

    {"URL":"https://example.com"}

Is reformated as:

    {
        "URL": "https:\/\/example.com"
    }

What do you think of reformatting rather like this?

    {
        "URL": "https://example.com"
    }

**Comment by gongo** [comment]
Please try `(setq json-reformat:pretty-string? t)` and reformat.

See: https://github.com/gongo/json-reformat#configuration

**Comment by psequeirag** [comment]
So nice! Thanks a lot!
