### ISSUE TITLE
Display the error line number

### ISSUE THREAD

**Issue by jlhg** [gongo/json-reformat#19]
The json-reformat will display `Bad string format: "doesn't start with '\"'!"` if there are some wrong formats in the file. However, it is difficult to trace where the error occurred.

How about adding more information to the error message, like json.tool module in Python: `Expecting property name: line 21 column 5 (char 514)`.

**Comment by gongo** [comment]
nice idea !

**Comment by gongo** [comment]
@jlhg 

I implemented this feature at version `20150319.628`. Please try !

**Comment by jlhg** [comment]
It works! :+1:
Thank you.
