### ISSUE TITLE
The slash symbol was escaped after formatting

### ISSUE THREAD

**Issue by jlhg** [gongo/json-reformat#21]
There is an unexpected and unreliable behavior when formatting a string such as file path:

Before:

```
{
  "js": ["to/some/path"]
}
```

After:

```
{
  "js": [
    "to\/some\/path"
  ]
}
```

The slash symbols were escaped.

**Comment by gongo** [comment]
@jlhg See https://github.com/gongo/json-reformat/issues/15#issuecomment-77054044

**Comment by jlhg** [comment]
Nice!
