### ISSUE TITLE
json-reformat-region changes content of json

### ISSUE THREAD

**Issue by torgeir** [gongo/json-reformat#23]
```js
{"test":{}}
```

followed by running `json-reformat-region` gives

```js
{
    "test": null
}
```

**Comment by gongo** [comment]
Sorry, it is difficult to solve this problem for me. Similar issue: https://github.com/gongo/json-reformat/issues/17#issuecomment-78046968

Thanks.

**Comment by torgeir** [comment]
Let me know if I should file his issue with another repo instead

**Comment by gongo** [comment]
Hi @torgeir 

It is scheduled to be resolved GH-24 :muscle:

**Comment by torgeir** [comment]
:thumbsup:

**Comment by gongo** [comment]
Hi @torgeir 

Sorry for the delay. I released v20150901.542. Please try !

**Comment by gongo** [comment]
ping @torgeir

**Comment by torgeir** [comment]
Alright! 

```
```

**Comment by gongo** [comment]
Thanks!!

**Comment by torgeir** [comment]
Thanks, yourself!
