### ISSUE TITLE
Format a single line?

### ISSUE THREAD

**Issue by arichiardi** [gongo/json-reformat#31]
Hello @gongo!

Wonderful package, very lean and tidy :)

I was wondering if it is possible to indent a single line only so that I can assign:

```
(setq-local indent-line-function #'json-reformat-line) ;; wishful thinking
(setq-local indent-region-function #'json-reformat-region)
```

Maybe something to add? :smiley_cat:

**Comment by gongo** [comment]
Hi @arichiardi 

Thanks for proposal.
But I can not imagine what kind of movement you expect to `json-reformat-line`.
Could you tell me what you are expecting for that function?

e.g.

Before:

![2017-04-22 10 42 43](https://cloud.githubusercontent.com/assets/124713/25300350/701605bc-2748-11e7-835b-46facceb7cfd.png)

After(1):

![2017-04-22 10 42 36](https://cloud.githubusercontent.com/assets/124713/25300354/7606dbcc-2748-11e7-8d70-21c8ed8c9cf5.png)

After(2):

![2017-04-22 10 42 23](https://cloud.githubusercontent.com/assets/124713/25300357/7bec734e-2748-11e7-8a6c-bb4270cb5ace.png)

other..?

**Comment by arichiardi** [comment]
Probably some sort of movement based on the indentation of the context around it? Don't even know if it is possible actually. Just brainstorming 😀
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arichiardi** [comment]
Probably after (1) is the less surprising of the two.

**Comment by gongo** [comment]
If you use `js-mode` , `js-indent-line` is assigned to `indent-line-function`.

**Comment by arichiardi** [comment]
I am using  `js2-mohe` and for some reason it keeps indenting 4 spaces instead of 2.

**Comment by gongo** [comment]
When js2-mode, `js2-indent-line` is assigned.


https://github.com/mooz/js2-mode/blob/master/js2-mode.el#L101-L105

**Comment by arichiardi** [comment]
I see, but wouldn't be better to have consistency? I think what I see now is that when I use yours it uses one kind of formatting and when I use `js2`'s I get another. I am also very familiar with Emacs internals so I might actually give this a shot sooner or later.

**Comment by gongo** [comment]
> to have consistency? 

I think there is a consistent between `json-reformat` and `js-mode` (`js2-mode`) if those indent-level equal.

```lisp
(setq json-reformat:indent-width 4)
(setq js2-basic-offset 4)
```

**Comment by arichiardi** [comment]
I thought I tried that, I will tried again.
