### ISSUE TITLE
Feature request: add a minify command (opposite of beautify)

### ISSUE THREAD

**Issue by Fuco1** [gongo/json-reformat#32]
Sometimes it would be handy to be able to minify the json back to a "single row".  Just doing naive replacement of whitespace might break the content of strings so I think this would require some minimal parsing.  Or maybe just adjusting the output of the beautifier with some settings.

**Comment by gongo** [comment]
Hi @Fuco1 

Thanks for request. But sorry, this library is formatter (beautifier). 
`minify` is not the role of this library. 🙇

**Comment by Fuco1** [comment]
I wasn't aware of the built-in library.  What I want can be done simply with

```
(let* ((p (point))
       (json (json-read)))
  (delete-region p (point))
  (save-excursion
    (insert (json-encode json))))
```

Thanks :)
