### ISSUE TITLE
Bind json-reformat-region to a key

### ISSUE THREAD

**Issue by Abhisek-** [gongo/json-reformat#35]
If you can bind `json-reformat-region` to a key like `C-c C-c r`(not sure whether this key is a good idea) or something like that, would be much appreciated.

**Comment by gongo** [comment]
How about this?

```lisp
(global-set-key (kbd "C-c C-c r") 'json-reformat-region)
```

**Comment by Abhisek-** [comment]
I'm not the right person to judge this as I haven't worked on `elisp` or even `lisp`. I'm merely a `python` guy. A quick search on google tells that this is great!

I could've created a pull request, but as I don't know the language, can't write test case for this.

But If I can be of any help, please let me know

**Comment by gongo** [comment]
I don't want to implement configuration of key-binding in json-reformat.el.
Because I want to write it in each individual `.emacs` .

> ```
> (global-set-key (kbd "C-c C-c r") 'json-reformat-region)
> ```

Bind can be set with the above code, please write in your `.emacs` .

**Comment by Abhisek-** [comment]
gotcha. I thought it was missing. Is there any downside if it ships with the package ?
