### ISSUE TITLE
Status of this library?

### ISSUE THREAD

**Issue by purcell** [gongo/json-reformat#46]
I see there are a few unresolved issues and open pull requests, but no commits have been made for 5 years. Is this package maintained, or should we at MELPA encourage a new potential maintainer to step up, e.g. @thisch?

If you're not planning to do any further maintenance yourself, you could either grant access to your repo to one or more co-maintainers, or transfer the repo to someone so that the issues/PRs are kept intact.

**Comment by gongo** [comment]
Hi @purcell 

This library is no longer needed since Emacs 24.4. Because there are builtin functions that have similar functionality since 24.4. (Most of the remaining issues and pull requests are resolved by those functions.)

So I think it's okay to archive this repository.

**Comment by thisch** [comment]
@gongo There are still some packages that depend on `json-reformat`, otherwise I can't explain why `json-reformat` is part of my list of downloaded emacs(-28) packages. If we change those packages to not depend on `json-reformat`, I'm fine with archiving this package.

**Comment by thisch** [comment]
I have https://github.com/joshwnj/json-mode/ in my init.el, which depends on `json-reformat`.

**Comment by purcell** [comment]
Thanks @gongo.

Yes, @thisch, it was `json-mode` I identified as requiring `json-reformat` in my config too. Probably we should submit a PR for `json-mode` that removes the dependency.
