### ISSUE TITLE
'loop' is an obsolete alias

### ISSUE THREAD

**Issue by diamond-lizard** [gongo/json-reformat#48]
When loading json-reformat 0.0.6 in Emacs 28.1, it complains:

    json-reformat.el: Warning: 'loop' is an obsolete alias (as of 27.1); use 'cl-loop' instead.

**Comment by gongo** [comment]
Hi @diamond-lizard 
I am terribly sorry for the late confirmation.

This issue was fixed in GH-42 and I've released 0.0.7 (in melpa,  `20220905.2342`)

**Comment by gongo** [comment]
By the way, `json-pretty-print` and `json-pretty-print-buffer` can be used since Emacs 24.4, so I recommend using it.
